name: Build and test

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main

    - name: Create build folder
      run: mkdir build

    - name: Install Conan dependencies
      working-directory: ${{github.workspace}}/build
      run: conan install .. -s build_type=${{env.BUILD_TYPE}} -pr:b=default --build=missing

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} "-DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake" -DCMAKE_POLICY_DEFAULT_CMP0091=NEW

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}